url: "https://franapoli.github.io"
baseurl: "/bioinfolab.github.io"

# Site settings
title: Bioinformatics Lab @ UniSannio
email: frnapolitano@unisannio.it
description: "Laboratory of Bioinformatics at University of Sannio"


# Team names, titles and social links
people:
- name: Luigi Cerulo
  pic: 1
  position: Associate Professor
  bio: [Work in progress...]
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Francesco Napolitano
  pic: 2
  position: Assistant Professor
  bio: [Work in progress...]
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

people2:
- name: Antonio Ammendola
  pic: 3
  position: PhD student
- name: Luca Faretra
  pic: 7
  position: Postgraduate Fellow
  bio: |
     <b>Master Thesis title</b>: "Assessing Event-Based Alternative Splicing Tools: A Comprehensive Benchmarking Study"<br><br>

     <b>Master Thesis abstract</b>: Alternative Splicing (AS) is an important step during
     maturation of primary transcripts as it allows to have different mRNA molecules from the same gene. These molecules code for different proteins that can have similar functions, but can also assume completely different functions. Based on this, to make a more accurate cell expression analysis, alternative splicing must be considered. Currently, there is a huge amount of tools that can analyze alternative splicing starting from RNA-Seq data and new tools are also constantly developed, but at the same time there is a lack of studies in which these tools are evaluated together, making it very difficult to choose the appropriate tool. In literature, AS tools are generally analyzed only with one RNA-Seq example, without considering that results may change depending on differing sequencing parameters, such as sequencing errors, read length, library size, etc. This is a limitation because various conditions may affect tool performance. In this thesis we developed a pipeline that permits to have near real RNA-Seq data with controlled parameters and we used it to test some event-based AS tools in order to observe how these affect performances. Essentially, our purpose is to contribute to enhancing the understanding and selection of AS tools for future RNA-Seq analyses. The findings highlight that various parameters may impact on the performance of event-based AS tools. The impact of these parameters varies depending on both the type of tool employed and the specific type of splicing event under analysis. Notably is the effect of fragment length on SUPPA's and rMATS's performance. While SUPPA outperforms rMATS for each type of event with short fragments, it exhibits a noticeable performance decline with longer fragments, rendering it inferior to rMATS in such instances. This decrease, however, is noticeable only in specific splicing events, particularly in ES, where SUPPA goes from an F-Score 17.20\% higher than that of rMATS (0.69 ± 0.007 vs. 0.59 ± 0.01) to a value 8.96\% lower (0.55 ± 0.01 vs. 0.61 ± 0.006). This emphasizes the criticality of selecting the appropriate tool based on the specific characteristics of starting data and the objectives of AS analysis.
- name: Diana Parente
  pic: 4
  position: Intern

people3:
- name: Donatella Pierri
  pic: 5
  position: Bachelor student
  bio: |
    <b>Bachelor Thesis title</b>: "Studio del centrosoma attraverso dati disponibili di trascrittomica" <br><br>

    <b>Bachelor Thesis abstract</b>: Questa tesi si propone di approfondire la comprensione dei meccanismi legati al centrosoma attraverso l'impiego della bioinformatica, concentrandosi in particolare sui programmi trascrizionali coinvolti. Al fine di raggiungere questo obiettivo, verranno identificati data set, di cui saranno fatte analisi preliminari, per individuare correlazioni significative e tendenze nei dati. Tale approccio consentirà di ottenere una visione più completa e dettagliata dei processi molecolari che regolano il centrosoma e la sua interazione con i programmi trascrizionali. Attraverso l'analisi bioinformatica dei dati di sequenziamento dell'mRNA, si potrebbero identificare varianti di splicing associate al centrosoma e studiarne l'impatto sulla biologia cellulare.
- name: Felicita Masone
  pic: 6
  position: Bachelor student
  bio: |
    <b>Bachelor Thesis title</b>:
    <b>Bachelor Thesis title</b>: This thesis focuses on developing a method, called RGDIST, to identify genes that are responsive to drug treatments. RGDIST is based on the assumption that these genes should show the effects of treatment more prominently in the cells closest to the site of drug injection. The study was applied to a spatial RNAseq dataset obtained after injections of heme in the mouse brain, with the aim of simulating intracerebral hemorrhage and evaluating the transcriptional effects of free heme in brain tissue. RGDIST was used to identify genes that are responsive to treatment and proved to be effective in detecting these genes more sensitively than other methods. The significant genes extracted with RGDIST are biologically relevant and consistent with the expected effects of the presence of free hemoglobin and heme. <br><br> Questa tesi si concentra sullo sviluppo di un metodo, chiamato RGDIST, per identificare i geni responsivi ad un trattamento farmacologico. RGDIST si basa sull'assunzione che questi geni debbano mostrare gli effetti del trattamento in modo più marcato nelle cellule più vicine al sito di iniezione del farmaco. Lo studio è stato applicato ad un dataset di spatial RNAseq ottenuto dopo iniezioni di eme nel cervello di topo, con lo scopo di simulare un'emorragia intracerebrale e valutare gli effetti trascrizionali dell'eme libero nel tessuto cerebrale. RGDIST è stato utilizzato per identificare i geni responsivi al trattamento e ha dimostrato di essere efficace nell'individuazione di questi geni in modo più sensibile rispetto ad altri metodi. I geni significativi estratti con RGDIST sono biologicamente rilevanti e coerenti con gli effetti attesi dalla presenza di emoglobina ed eme liberi.
- name: Francesco Saccomando Ciaramella
  pic: 8
  position: Intern, Bachelor student
  bio: |
    <b>Bachelor Thesis title</b>:
    The thesis focuses on revDECCODE, a computational method for identifying small molecules through differential profiles, for integration into standard therapies for glioblastoma (GBM) treatment. Glioblastoma represents one of the most aggressive forms of brain cancer, with limited therapeutic options and a poor prognosis. The first chapter introduces the biological context of glioblastoma, highlighting its molecular complexity. The second chapter explores the application of transcriptomics in the context of drug discovery against cancer, specifically targeting GBM. In the third chapter, the revDECCODE method is presented as an approach for identifying small molecules with therapeutic potential in glioblastoma. Through the analysis of differential profiles, revDECCODE enables the extraction of molecules that may act synergistically with standard therapies, improving treatment efficacy and reducing pharmacological resistance. The integration of methods like revDECCODE into therapeutic strategies for glioblastoma offers new perspectives for addressing this devastating disease. The thesis concludes by emphasizing the importance of omics research and analyzing potential future scenarios.<br><br>
    La tesi si focalizza revDECCODE metodo computazionale per l'identificazione di piccole molecole, attraverso profili differenziativi, per l'integrazione nelle terapie standard per il trattamento del glioblastoma (GBM). Il glioblastoma rappresenta una delle forme più aggressive di tumore cerebrale, con limitate opzioni terapeutiche e prognosi sfavorevole. Il primo capitolo introduce il contesto biologico del glioblastoma, evidenziandone la complessità molecolare. Il secondo capitolo esplora l'applicazione della trascrittomica nel contesto della drug discovery contro il cancro e poi nello specifico contro il GBM. Nel terzo capitolo, viene presentato il metodo revDECCODE come approccio per l'identificazione di piccole molecole con potenziale terapeutico nel glioblastoma. Attraverso l'analisi di profili differenziativi, revDECCODE permette l'estrazione di molecole che potrebbero agire sinergicamente con le terapie standard, migliorando l'efficacia del trattamento e riducendo la resistenza farmacologica. L'integrazione di metodi come revDECCODE nelle strategie terapeutiche per il glioblastoma offre nuove prospettive per affrontare questa malattia devastante. La tesi viene conclusa sottolineando l'importanza della ricerca omica e analizzandone i possibili scenari in divenire.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
permalink: pretty
