url: "https://franapoli.github.io"
baseurl: "/bioinfolab.github.io"

# Site settings
title: Bioinformatics Lab @ UniSannio
email: frnapolitano@unisannio.it
description: "Laboratory of Bioinformatics at University of Sannio"

collections:
  team:
    output: true
  tools:
    output: true


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: via dei Mulini
  - line: Benevento, Italy

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
permalink: pretty
